name: process-artifacts

on:
  workflow_run:
    workflows: ["my-workflow"]  # The name of the first pipeline
    types:
      - completed

jobs:
  process:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: artifacts

    - name: Checkout artifacts-store branch
      run: |
        git fetch origin
        git switch artifacts-store || git switch -b artifacts-store

    - name: Add, commit, and push artifacts
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER_EMAIL: ${{ secrets.MY_USER_EMAIL }}
        GITHUB_USER_NAME: ${{ secrets.MY_USER_NAME }}
      run: |
        git config --global user.email "$MY_USER_EMAIL"
        git config --global user.name "$MY_USER_NAME"
        cp -R artifacts/* .
        git add .
        git commit -m "Add downloaded artifacts" || echo "No changes to commit"
        git push origin artifacts-store
