name: Deploy Artifacts

on:
  workflow_run:
    workflows: ["my-workflow"]  
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout artifacts-store branch
      uses: actions/checkout@v4
      with:
        ref: artifacts-store

    - name: Set up Git configuration
      run: |
        git config --global user.email "${{ secrets.MY_USER_EMAIL }}"
        git config --global user.name "${{ secrets.MY_USER_NAME }}"

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        name: build-artifacts
        path: artifacts

    - name: Add artifacts to the repository
      run: |
        cp -R artifacts/* .
        git add .
        git commit -m "Deploy artifacts from build" || echo "No changes to commit"
        git push origin artifacts-store
