name: Download Artifacts

on:
  workflow_run:
    workflows: ["my-workflow"]  
    types:
      - completed

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout artifacts-store branch
      uses: actions/checkout@v4

    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: ./downloaded-artifacts

    - name: Add artifacts to the repository
      run: |
        cp -R artifacts/* .
        git add .
        git commit -m "Deploy artifacts from build" || echo "No changes to commit"
        git push origin artifacts-store