name: my-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # - name: Run tests with Maven
    #   run: mvn test

    - name: Archive build artifacts
      run: mkdir -p artifacts && cp target/*.jar artifacts/

    - name: Checkout artifacts-store branch
      uses: actions/checkout@v4
      with:
        ref: artifacts-store

    - name: Copy artifacts to artifacts-store branch
      run: |
        cp -R artifacts/* .
        git config --global user.email "kumar.akash.beehyv@gmail.com"
        git config --global user.name "devops1406-ak"
        git add .
        git commit -m "Add build artifacts"
        git push origin HEAD:artifacts-store