name: my-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
        - name: Code Checkout
          uses: actions/checkout@v4
          
      