name: my-workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      name: Checkout code

    - name: Set up JDK 11 for x64
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        architecture: x64
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Run tests with Maven
      run: mvn test

    - name: Archive build artifacts
      run: |
        mkdir -p artifacts
        cp target/*.jar artifacts/ || echo "No artifacts found to copy"
        

    - name: Stash untracked files
      run: git stash --include-untracked || true

    - name: Checkout artifacts-store branch
      run: |
        git fetch origin
        git switch artifacts-store || git switch -b artifacts-store
        git stash pop || true

    - name: Merge remote changes and push artifacts
      run: |
        git pull --rebase origin artifacts-store || true
        cp -R artifacts/* .
        git config --global user.email "kumar.akash.beehyv@github.com"
        git config --global user.name "devops1406-ak"
        git add .
        git commit -m "Add build artifacts" || echo "No changes to commit"
        git push origin artifacts-store
